### ISSUE TITLE
Heap out of memory with "ui5 use sapui5@1.76.0"

### ISSUE THREAD

**Issue by csnv** [SAP/ui5-tooling#495] opened 2021-02-15 13:38 UTC
## Expected Behavior
Command runs fine and dependency on sapui5/1.76.0 is added to ui5.yaml config file

## Current Behavior
Node GC runs out of memory when running command

## Steps to Reproduce the Issue

1. Install @ui5/cli with `npm install @ui5/cli` in a large cordova/sapui5 project.
2. Run `npx ui5 init` to create the initial config file
3. Run `npx ui5 use sapui5@1.76.0`

## Context
 * UI5 Module Version (output of `ui5 --version` when using the CLI): **`2.10.0`**
 * Node.js Version: **`14.15.5`**
 * npm Version: `7.5.4`
 * OS/Platform: `Windows`
 * Browser *(if relevant)*: `unknown`
 * Other information regarding your environment *(optional)*: `nothing`

## Log Output / Stack Trace
````
verb normalizer:translators:npm Deduping pending dependency micromatch with parent path :com.enel.ptw:gulp-cli:matchdep:findup-sync:micromatch:extglob:
verb normalizer:translators:npm Deduping pending dependency micromatch with parent path :com.enel.ptw:gulp-cli:liftoff:findup-sync:micromatch:extglob:
verb normalizer:translators:npm Deduping pending dependency micromatch with parent path :com.enel.ptw:gulp:glob-watcher:anymatch:micromatch:extglob:
verb normalizer:translators:npm Deduping pending dependency micromatch with parent path :com.enel.ptw:gulp:gulp-cli:matchdep:micromatch:extglob:
verb normalizer:translators:npm Deduping pending dependency micromatch with parent path :com.enel.ptw:gulp-cli:matchdep:micromatch:extglob:

<--- Last few GCs --->

[23540:000001B2509E8B70]   500533 ms: Mark-sweep (reduce) 4095.6 (4102.1) -> 4095.6 (4104.1) MB, 3933.3 / 0.0 ms  (average mu = 0.071, current mu = 0.001) allocation failure scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory
 1: 00007FF6FC61058F napi_wrap+109311
 2: 00007FF6FC5B52B6 v8::internal::OrderedHashTable<v8::internal::OrderedHashSet,1>::NumberOfElementsOffset+33302
 3: 00007FF6FC5B6086 node::OnFatalError+294
````

**Comment by RandomByte** [comment] 2021-02-15 19:06
Thanks for reporting. I'll close this as a duplicate of https://github.com/SAP/ui5-tooling/issues/311

I also added additional information there, explaining the cause and possible workarounds for that issue.

In your case it seems that "gulp" or "gulp-cli" is part of the dependency tree. So maybe you could try to go with [Option 1](https://github.com/SAP/ui5-tooling/issues/311#issuecomment-779401749) and move Gulp to the `devDependencies` of your project since its probably not required outside of development. Of course I can be mistaken since I don't know your project or dev setup.

**Closed by RandomByte** 2021-02-15 19:06 UTC
Labels: bug, needs triage
