### ISSUE TITLE
Cannot run 'ui5 serve' command when using @sap/approuter

### ISSUE THREAD

**Issue by IObert** [SAP/ui5-tooling#86] opened 2018-11-19 13:42 UTC
## Expected Behavior
The script should start the ui5 app

## Current Behavior
The console prints:
```
TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at ProjectPreprocessor.loadProjectConfiguration
```

## Steps to reproduce the issue
1. Add the app router to the dependencies in the package.json file (could be of any UI5 app, eg the demo application)
  `"@sap/approuter": "^5.8.0"`
2. Run the serve command
  `ui5 serve`

## Context
- UI5 Module Version *(output of `ui5 --version` when using the CLI)*: `1.60`
- Node.js Version: `v10.6.0`
- npm Version: `6.4.1`
- OS/Platform: MacOS 10.14.1 (18B75)

## Affected components *(if known)*
- [ ] [ui5-builder](https://github.com/SAP/ui5-builder)
- [ ] [ui5-server](https://github.com/SAP/ui5-server)
- [ ] [ui5-cli](https://github.com/SAP/ui5-cli)
- [ ] [ui5-fs](https://github.com/SAP/ui5-fs)
- [X] [ui5-project](https://github.com/SAP/ui5-project)
- [ ] [ui5-logger](https://github.com/SAP/ui5-logger)

## Log Output / Stack Trace
```
TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at ProjectPreprocessor.loadProjectConfiguration
```

**Comment by RandomByte** [comment] 2018-11-19 21:40
Seems to be a duplicate of https://github.com/SAP/ui5-project/issues/50

**Comment by matz3** [comment] 2018-11-22 16:43
Closing as duplicate

**Closed by matz3** 2018-11-22 16:43 UTC
