### ISSUE TITLE
archive.zip is empty

### ISSUE THREAD

**Issue by AlexNecula-Cashtriba** [SAP/ui5-tooling#555] opened 2021-09-09 13:58 UTC
## Expected Behavior
The contents of the dist folder should be inside archive.zip

## Current Behavior
archive.zip remains

## Steps to Reproduce the Issue
Exceute command: npm run deploy
1. Build successfull
2. Press y to start deployment
3. message "Create Archive" is shown
4. message "Starting Deployment on <location> (11/11) Running task deploy-to-abap" is shown. Expected to have multiple lines, one for each file that should be placed inside the archive
5. Error 400 is shown given by the backend on the archive check (the archive.zip file is empty)

## Context
 * UI5 Module Version (output of `ui5 --version` when using the CLI): **`2.12.1`**
 * Node.js Version: **`15.10.0`**
 * npm Version: `7.22.0`
 * OS/Platform: `Windows 10 x64`
 * Browser *(if relevant)*: `not relevant`
 * Other information regarding your environment *(optional)*: `ui5-deploy.yaml: https://www.protectedtext.com/ui5-arhive-empty
 Password: ui5
 
 The information hidden with <> is correct. The connection to the backend is working.
 
 The deploy command from package.json: "deploy": "ui5 build preload --clean-dest --config ui5-deploy.yaml --include- 
 task=generateManifestBundle generateCachebusterInfo",`

## Log Output / Stack Trace
This is between the Create Archive and the 400 return from the backend. Folder name obfuscated.

```
info builder:custom deploy-to-abap Create Archive
verb resources:tracing:total ==========================
verb resources:tracing:total [=> TRACE SUMMARY:
verb resources:tracing:total   2.54 s elapsed time
verb resources:tracing:total   30 trace calls
verb resources:tracing:total   8 glob executions
verb resources:tracing:total   28 path stats
verb resources:tracing:total   4 rl-collections involed:
verb resources:tracing:total       15x source of <folder_name>
verb resources:tracing:total       6x <folder_name>
verb resources:tracing:total       2x dependencies of <folder_name>
verb resources:tracing:total       1x generateComponentPreload - prioritize workspace over dependencies: <folder_name>
verb resources:tracing:total ======================]
info builder:custom deploy-to-abap Starting Deployment.
ERR! builder:custom deploy-to-abap Request failed with status code 400==========
```

**Comment by RandomByte** [comment] 2021-09-09 14:07
I think this is a duplicate of https://github.com/SAP/ui5-tooling/issues/554

**Closed by RandomByte** 2021-09-09 14:07 UTC
Labels: bug, needs triage
