### ISSUE TITLE
Links to builder tasks and processors are broken (404)

### ISSUE THREAD

**Issue by vobu** [SAP/ui5-tooling#227] opened 2020-04-15 18:49 UTC
Links to `builder` tasks and processors -> `404`
## Expected Behavior
Page with available tasks and processors is shown

## Current Behavior
404

## Steps to reproduce the issue
Click on link to tasks or processors on https://sap.github.io/ui5-tooling/pages/Builder/

**Comment by RandomByte** [comment] 2020-04-16 13:06
Thanks! Closing as duplicate of https://github.com/SAP/ui5-builder/issues/446

**Closed by RandomByte** 2020-04-16 13:06 UTC
Labels: duplicate
