### ISSUE TITLE
Missing thirdparty licence file after ui5 build with project shims

### ISSUE THREAD

**Issue by CLVNSwan** [SAP/ui5-tooling#563] opened 2021-09-16 11:12 UTC
## Expected Behavior
File in node_modules folders with no extension should be also copied to local dist folder eg. filename "LICENSE"
(LICENSE.txt is still working)

## Current Behavior
License file in thirdparty library, eg. lodash, is missing in 'dist' folder after the ui5 build is done over ui5 tooling

## ui5.yaml

example from [UI5 CLI Page](https://sap.github.io/ui5-tooling/pages/Configuration/#extension-configuration)

      specVersion: "2.5"
      type: application
      metadata:
        name: my.application
      ---
      specVersion: "2.5"
      kind: extension
      type: project-shim
      metadata:
        name: my.application.thirdparty
      shims:
        configurations:
          lodash:
            specVersion: "2.5"
            type: module
            metadata:
              name: lodash
            resources:
              configuration:
                paths:
                  /resources/my/application/thirdparty/: ""

## Context
 * UI5 tooling specVersion: "2.5"
 * npm Version: `6.14.6`
 * os: windows 10
 * terminal: git bash

**Comment by codeworrior** [comment] 2021-09-16 11:21
Duplicate of #546, fixed with [`@ui5/builder` 2.9.5](https://github.com/SAP/ui5-builder/blob/master/CHANGELOG.md#v295---2021-08-25) which is included in the most recent [`@ui5/cli` 2.12.1](https://github.com/SAP/ui5-cli/blob/master/CHANGELOG.md#v2121---2021-08-25).

**Comment by codeworrior** [comment] 2021-09-16 11:24
Well, shims might have a special impact, so re-opening until you either confirm that 2.12.1 fixes the problem or until you provide new details.

**Comment by CLVNSwan** [comment] 2021-09-16 11:35
I was still on 2.12.0 and the problem is fixed by 2.12.1. I am sorry! Thanks for the hint

**Closed** 2021-09-16 11:35 UTC
Labels: bug, duplicate, module/ui5-builder
