### ISSUE TITLE
No code suggestions/auto-completion for `ui5.yaml` based on JSON schema

### ISSUE THREAD

**Issue by pubmikeb** [SAP/ui5-tooling#560] opened 2021-09-13 14:27 UTC
For SAP UI5 Tooling `ui5.yaml` there is a JSON schema https://sap.github.io/ui5-tooling/schema/ui5.yaml.json, which is supposed to assist when working with `ui5.yaml`.

The problem is that this schema doesn't provide a code suggestions/auto-completion aka IntelliSense.
More precisely, it does it but only for the two items: `specVersion` and `kind`:

![13_162203](https://user-images.githubusercontent.com/17231333/133100983-1b24cabd-c733-486a-81fb-5cf2bec8d4f1.png)

And when I chose `specVersion`, it suggests me a version number: `2.5`, `2.4`, etc. But when I chose one of the proposed values, it turns out that it's `specVersion: 2.5` instead of required `specVersion: "2.5"`, so the `specVersion` is proposed as a number rather than a string.

For the rest of the items there is no suggestions at all.

## Context
 * UI5 Module Version (output of `ui5 --version` when using the CLI): **`"@ui5/cli": "^2.12.1"`**
 * Node.js Version: **`16.9.1`**
 * npm Version: `7.23.0`
 * OS/Platform: `Winndows 10 x64 21H1`

**Comment by RandomByte** [comment] 2021-09-20 09:22
Once you declared a specification version greater than 2 (e.g. `specVersion: "2.5"`), additional suggestions should come up. Can you confirm that?

It's indeed an issue that the autocompletion does not put the version number into quotes. I'm not sure whether this is an issue with the schema or the way we validate it though.

**Comment by pubmikeb** [comment] 2021-09-20 20:28
> _Can you confirm that?_

No! That's the point, no suggestions appear:

![20_222203](https://user-images.githubusercontent.com/17231333/134070121-96d92cd1-e2a4-4ae3-b084-66bd717a838c.png)

> _It's indeed an issue that the auto-completion does not put the version number into quotes. I'm not sure whether this is an issue with the schema or the way we validate it though._

It's a schema problem, there is a need to add `"type": "string"` to the `specVersion` definition:

```json
"specVersion": {
  "enum": [
    "2.5",
    "2.4",
    "2.3",
    "2.2",
    "2.1",
    "2.0",
    "1.1",
    "1.0",
    "0.1"
  ],
  "type": "string",
  "errorMessage": "Unsupported \"specVersion\"\nYour UI5 CLI installation might be outdated.\nSupported specification versions: \"2.5\", \"2.4\", \"2.3\", \"2.2\", \"2.1\", \"2.0\", \"1.1\", \"1.0\", \"0.1\"\nFor details see: https://sap.github.io/ui5-tooling/pages/Configuration/#specification-versions"
}
```

**Comment by RandomByte** [comment] 2021-09-22 12:08
> > _Can you confirm that?_
> 
> No! That's the point, no suggestions appear:
> 
> ![20_222203](https://user-images.githubusercontent.com/17231333/134070121-96d92cd1-e2a4-4ae3-b084-66bd717a838c.png)

This I cannot reproduce. Once a spec-version >2 is set, suggestions work with the LSP-yaml plugin for Sublime Text:
![Screenshot 2021-09-22 at 14 05 32](https://user-images.githubusercontent.com/1589939/134340579-4261c809-fe6a-41b1-be3a-340ee95d7a17.png)

May I ask which IDE (and schema-plugin, if any) you are using?


> It's a schema problem, there is a need to add `"type": "string"` to the `specVersion` definition:

Thanks! We will look into it 👍

**Comment by pubmikeb** [comment] 2021-09-22 18:48
> May I ask which IDE (and schema-plugin, if any) you are using?

IntelliJ IDEA 2021.2.2

Schema file:
https://sap.github.io/ui5-tooling/schema/ui5.yaml.json

What do you mean under «schema-plugin»?

**Comment by RandomByte** [comment] 2021-09-28 08:56
@matz3 could you look into the missing `"type": "string"` declaration mentioned in https://github.com/SAP/ui5-tooling/issues/560#issuecomment-923271887 ?

I asked @svbender to check whether he can reproduce the missing suggestions in WebStorm

**Comment by matz3** [comment] 2021-09-28 10:21
Even when adding `"type": "string"`, the auto-suggestion (via https://github.com/redhat-developer/yaml-language-server) uses a number.
So this seems to be a bug in the yaml-language-server.

@pubmikeb can you confirm that adding `"type": "string"` solves this problem in your IDE?

**Comment by pubmikeb** [comment] 2021-09-28 20:44
> _Can you confirm that adding `"type": "string"` solves this problem in your IDE?_

I've tested the case on two file types:

1. On JSON-file, there everything is OK:

![28_224142](https://user-images.githubusercontent.com/17231333/135162550-6c243556-70f0-4750-9d4b-1de4f979b00d.png)

2. On YAML-file, there `"type": "string"` doesn't ensure a string-type for the proposed value.

**Comment by svbender** [comment] 2021-09-29 09:51
I have tested the schema with WebStorm and can reproduce the issues.

1. If you start with an empty `ui5.yaml` the IDE proposes to add the missing requirements `specVersion` and `type`, if I accept it, they are added with 1 indentation (2 spaces) which results in further confusion because there is no auto-completion for both and on top level the auto-completion suggests another `specVersion` entry. You need to remove the spaces.
	
2. Auto-completion suggestions for `kind` are working but not for `type`. The good thing is that in the "Problems" tab/window of the IDE all possible enum values are shown correctly. For example:
`Schema validation: Value should be one of: "application", "library", "theme-library", "module"`

3. The `specVersion` string handling is not working as expected. Auto-completion is showing all available versions but they are not added with quotes.
    - Adding `"type":"string"` to `specVersion` in the schema has no effect beside that the IDE shows the problem `Schema validation: Incompatible types. Required: string. Actual: number.`. The quotes are not added automatically.
    - Adding single quotes in the schema works, but had the effect that the validator is not able to recognize the value even if it is in the enum list: `Schema validation: Value should be one of: "2.5", "'2.4'", "2.3", "2.2", "2.1", "2.0", "1.1", "1.0", "0.1"`

I think this issues are related to the IDE and the used parser.

WebStorm/IntelliJ is not using a separate plugin for that, it is a built-in feature. The schema is used automatically from https://www.schemastore.org/json/ , but you can overwrite the usage in the configuration: https://www.jetbrains.com/help/ruby/yaml.html#remote_json (It should be the same configuration for all IntelliJ based IDEs.)

**Comment by pubmikeb** [comment] 2021-09-29 16:10
I've opened a ticket at WebStorm:
https://youtrack.jetbrains.com/issue/WEB-52885

**Comment by matz3** [comment] 2023-02-21 10:29
Closing, as it's a third-party issue.

**Closed by matz3** 2023-02-21 10:29 UTC
Labels: bug, needs triage, module/ui5-project
