### ISSUE TITLE
[@ui5/server@2.4.0]: Unknown Middleware XXX 

### ISSUE THREAD

**Issue by petermuessig** [SAP/ui5-tooling#591] opened 2021-12-26 08:40 UTC
## Expected Behavior
When using the UI5 Tooling in combination with Karma, configured middlewares in the `ui5.yaml` should be properly resolved and Karma will not fail on startup.

## Current Behavior
The Karma test fails with the issue `Unknown Middleware XXX`.

## Steps to Reproduce the Issue
1. Checkout https://github.com/ui5-community/ui5-ecosystem-showcase/pull/548/commits/d9980ceff460e220499be97f8aea01bf0515f334
2. Run `yarn --ignore-engines`
3. Run the Karma tests with `yarn test:opa5-ci`
4. Result: **No issue**
5. Remove the `@ui5/server@2.3.1` in the workspace root `package.json` and run `yarn --ignore-engines` again
6. Run the Karma tests with `yarn test:opa5-ci` again
7. Result: **ERROR**

Although the same NPM package of the `@ui5/server` version is used, the error occurs. I upgraded the `@ui5/cli` and the `karma-ui5` plugin to the latest version so that the common `@ui5/server@2.4.0` version is used. With the previous version `2.3.1` all works fine.

## Context
 * UI5 Module Version (output of `ui5 --version` when using the CLI): `2.14.2`
 * Node.js Version: `17.0.1`
 * Yarn Version: `1.22.17`
 * OS/Platform: `MacOS`
 * Browser *(if relevant)*: `not relevant`
 * Other information regarding your environment *(optional)*: `nothing`

## Log Output / Stack Trace

```sh
> SAPDevelop/ghdesktop/ui5-ecosystem-showcase [pr/548] M?? % yarn test:opa5-ci    
yarn run v1.22.17
$ cd packages/ui5-app && karma start karma-ci.conf.js
info normalizer:translators:ui5Framework Using OpenUI5 version: 1.95.0
26 12 2021 09:27:29.411:ERROR [ui5.framework]: Error: middlewareRepository: Unknown Middleware ui5-middleware-servestatic
    at Object.getMiddleware (/Users/XXXXXX/SAPDevelop/ghdesktop/ui5-ecosystem-showcase/node_modules/@ui5/server/lib/middleware/middlewareRepository.js:19:9)
    at MiddlewareManager.addMiddleware (/Users/XXXXXX/SAPDevelop/ghdesktop/ui5-ecosystem-showcase/node_modules/@ui5/server/lib/middleware/MiddlewareManager.js:50:47)
    at MiddlewareManager.addCustomMiddleware (/Users/XXXXXX/SAPDevelop/ghdesktop/ui5-ecosystem-showcase/node_modules/@ui5/server/lib/middleware/MiddlewareManager.js:237:15)
    at MiddlewareManager.applyMiddleware (/Users/XXXXXX/SAPDevelop/ghdesktop/ui5-ecosystem-showcase/node_modules/@ui5/server/lib/middleware/MiddlewareManager.js:38:14)
    at async Framework.setupUI5Server (/Users/XXXXXX/SAPDevelop/ghdesktop/ui5-ecosystem-showcase/node_modules/karma-ui5/lib/framework.js:491:3)
    at async Framework.setupMiddleware (/Users/XXXXXX/SAPDevelop/ghdesktop/ui5-ecosystem-showcase/node_modules/karma-ui5/lib/framework.js:534:17)
    at async Framework.init (/Users/XXXXXX/SAPDevelop/ghdesktop/ui5-ecosystem-showcase/node_modules/karma-ui5/lib/framework.js:286:3)
    at async init (/Users/XXXXXX/SAPDevelop/ghdesktop/ui5-ecosystem-showcase/node_modules/karma-ui5/lib/index.js:7:3)
    at async Promise.all (index 0)
    at async Server._start (/Users/XXXXXX/SAPDevelop/ghdesktop/ui5-ecosystem-showcase/node_modules/karma/lib/server.js:207:5)
    at async Server.start (/Users/XXXXXX/SAPDevelop/ghdesktop/ui5-ecosystem-showcase/node_modules/karma/lib/server.js:151:7)
    at async Object.exports.run (/Users/XXXXXX/SAPDevelop/ghdesktop/ui5-ecosystem-showcase/node_modules/karma/lib/cli.js:308:9)
26 12 2021 09:27:29.414:ERROR [karma-server]: Server start failed on port 9876: Error: ui5.framework failed. See error message above
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by matz3** [comment] 2022-01-10 09:55
Looks like a duplicate of https://github.com/SAP/ui5-tooling/issues/302

**Comment by RandomByte** [comment] 2022-01-12 16:43
I'm unable to checkout the referenced commit https://github.com/ui5-community/ui5-ecosystem-showcase/commit/d9980ceff460e220499be97f8aea01bf0515f334

```sh
ui5-ecosystem-showcase main❯ git checkout d9980ceff460e220499be97f8aea01bf0515f334
fatal: reference is not a tree: d9980ceff460e220499be97f8aea01bf0515f334
```

Also note the warning on GitHub:
> This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.

But yes, most likely a duplicate of #302. Make sure to remove all node_modules directories and check what is installed with `yarn list --pattern @ui5/server`

**Closed by RandomByte** 2022-01-12 16:43 UTC
Labels: bug, needs triage
