### ISSUE TITLE
Build and Tree commands fail with an AllocationError

### ISSUE THREAD

**Issue by dfenerski** [SAP/ui5-tooling#511] opened 2021-03-27 17:44 UTC
Project with the following structure 

![image](https://user-images.githubusercontent.com/48520530/112729241-e1d70000-8f33-11eb-8c3f-d7690a9166ea.png) 

cannot be built. Both of the commands fail after ~3 minutes with an 
<pre>
FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory. 
</pre>
This is the last verbose command it reaches before crashing: 
<pre>
verb normalizer:translators:npm Deduping pending dependency raw-body with parent path :board:@ui5/cli:@ui5/server:body-parser:raw-body:http-errors:statuses:
</pre>

My ui5.yaml file looks like this

<pre>
specVersion: '2.3'
metadata:
  name: board
type: application
framework:
  name: OpenUI5
  version: '1.78.18'
  libraries:
    - name: sap.m
    - name: sap.ui.core
builder:
  bundles:
    - bundleDefinition:
        name: com/AppName/Component-preload.js
        defaultFileTypes:
          - '.js'
          - '.json'
          - '.xml'
          - '.html'
          - '.library'
        sections:
          - mode: raw
            filters:
            #   - be/wl/PersonSkills/regenerator-runtime/runtime.js
          - mode: preload
            filters:
              - com/AppName/manifest.json
              - com/AppName/assets/**
              - com/AppName/fragment/**
              - com/AppName/controller/**
              - com/AppName/Component.js
              - com/AppName/i18n/**
              - com/AppName/model/**
              - com/AppName/util/**
              - com/AppName/view/**
              - com/AppName/lib/**
              - com/AppName/test/**
            resolve: false
            sort: true
            declareModules: false
      bundleOptions:
        optimize: true
        usePredefineCalls: true
  customTasks:
    - name: babel
      afterTask: replaceVersion
---
specVersion: '1.0'
kind: extension
type: task
metadata:
  name: babel
task:
  path: transpile.task.js
</pre>

I am following [this](https://blogs.sap.com/2019/08/28/ui5-tooling-custom-transpiler-babel-builder-extension-task/) guide to add a custom task since the project uses extensively ES6 features and up. The transpile.task.js is an exact copy of the code from the blog. I would also switch the internal parser if that would be a solution because after reading the issues I found out that only it lacks ES6 support.  

As far as I can tell, the process is this long and causes an exception because it parses stuff it is not supposed to. How do I tell the builder to ignore node_modules, if that indeed is the cause?

Any help is appreciated.

## Context
 * UI5 Module Version: 2.10.2
 * Node.js Version: 14
 * npm Version: 7
 * OS/Platform: ubuntu 20

**Comment by codeworrior** [comment] 2021-03-27 18:17
Sounds to me like a duplicate of #311. 

Please check whether the workarounds mentioned in @RandomByte's [comment](https://github.com/SAP/ui5-tooling/issues/311#issuecomment-779401749) can help in your case, too.

**Comment by dfenerski** [comment] 2021-03-27 21:04
Making the dependencies devDependencies worked, but referenced packages from node_modules didn't get bundled. Plus we later have a pipeline that runs a npm i, so now it wont install anything. 

Is there something I could do about those 2 issues or should I go back to the grunt setup we already have?

**Closed** 2021-03-28 11:13 UTC
Labels: bug, needs triage
