### ISSUE TITLE
Support Symbolic Links inside webapp folder

### ISSUE THREAD

**Issue by MichaelFlucher** [SAP/ui5-tooling#570] opened 2021-10-04 16:09 UTC
## Is your feature request related to a problem? Please describe.
I'm using a symbolic link to i18n folder and some libraries to reuse it across multiple apps inside my mta. For now I first need to ZIP the folder and link the ui5.yaml to this one for building.

## Describe the solution you'd like
Set `followSymbolicLinks` to `true`: https://github.com/SAP/ui5-fs/blob/5ff43e2a6dc05028893edb46d5580713a148ce1e/lib/adapters/FileSystem.js#L46 

## Describe alternatives you've considered
Powershell Buildscript, still annoying and needs two ui5.yaml, one for local development and one for building.

## Additional context
-

**Comment by RandomByte** [comment] 2021-10-05 13:24
I think this is a duplicate of https://github.com/SAP/ui5-tooling/issues/454

**Closed by RandomByte** 2021-10-05 13:24 UTC
Labels: enhancement
