### ISSUE TITLE
Unable to initialize UI5 CLI

### ISSUE THREAD

**Issue by ArnaudBuchholz** [SAP/ui5-tooling#833] opened 2023-05-29 15:41 UTC
I made a fresh install of an app based on `@ui5/cli` and I cannot execute `ui5`

## Expected Behavior
I can serve my app

## Current Behavior
`ui5` fails with message 
```text
Fatal Error: Unable to initialize UI5 CLI
```

## Steps to Reproduce the Issue

Because of the stack trace, I suspect this is related to the missing `APDDATA` environment variable.

![image](https://github.com/SAP/ui5-tooling/assets/4194952/34256693-c90d-49d6-95c3-e806f7aa5261)

## Context
 * @ui5/cli 3.1.2
 * Node.js Version: 18.16.0
 * npm Version: 9.5.1
 * OS/Platform: Windows 11
 * Browser *(if relevant)*: N/A
 * Other information regarding your environment *(optional)*: VS Studio Code terminal

## Log Output / Stack Trace

See screenshot

**Comment by ArnaudBuchholz** [comment] 2023-05-29 15:43
Important info : I confirm the behavior is specifc to the VS Studio Code terminal that does **not** define `APPDATA`
Having a fallback mechanism could help ;-)

**Comment by RandomByte** [comment] 2023-05-29 20:00
Thanks for reporting. This looks like a regression in `@pnpm/npm-conf`, which is a transitive dependency of [`update-notifier`](https://www.npmjs.com/package/update-notifier), which we where considering to remove/replace before.

It's a fork of another project, where exactly this problem seems to have been fixed a while ago: https://github.com/kevva/npm-conf/pull/7

But the issue got reintroduced in the fork later on: https://github.com/pnpm/npm-conf/commit/ccf74c4977a4ada380331a3811488486795f3085#diff-b34f2f53ab94368c86775969fb604e8375abe03b6a378bdd09896fd91ac0a0d2R30

Since the fork has not enabled issues, we should report it to their main project in the coming days: https://github.com/pnpm/pnpm/issues

**Comment by RandomByte** [comment] 2023-06-09 08:29
Reported via https://github.com/pnpm/pnpm/issues/6659

I'll close this issue for the time being. Please let us know if this becomes more critical.

**Closed by RandomByte** 2023-06-09 08:29 UTC
Labels: bug, needs triage

**Comment by RandomByte** [comment] 2023-06-14 08:31
https://github.com/pnpm/pnpm/issues/6659 got fixed and `@ui5/cli` `main` has been [updated](https://github.com/SAP/ui5-cli/commit/bc96d690b48aefdcaa3f01368a18999e184e0394#diff-44a7c69871c5958e657226d5552c9451606a778233fb824f68530d0cfd3f8994R974).

Your issue should be resolved with the next release of `@ui5/cli`
