### ISSUE TITLE
[ui5/cli] npm-shrinkwrap.json causing registry in .npmrc to be ignored

### ISSUE THREAD

**Issue by rishabh2408** [SAP/ui5-tooling#517] opened 2021-04-28 13:56 UTC
## Expected Behavior
Setting registry value in the .npmrc file should allow node modules to be downloaded from a private registry.

## Current Behavior
ui5/cli itself comes from the registry mentioned in .npmrc but the dependency of ui5/cli comes from open source npmjs.org

## Steps to Reproduce the Issue

1. Set private registry in .npmrc
2. Set package-lock as true in .npmrc
3. Do `npm i`
4. Check registry link in package-lock.json for ui5/cli dependencies.

## Possible reason:

[`npm-shrinkwrap.json`](https://github.com/SAP/ui5-cli/blob/master/npm-shrinkwrap.json) is present when ui5/cli is installed, as this has resolution links set as npmjs.org the registry in the .npmrc is ignored while fetching the dependencies of ui5/cli.

**Comment by tobiasso85** [comment] 2021-05-03 08:50
Hi @rishabh2408,

thanks for reporting this issue.

### Steps to reproduce
I cloned the openui5-sample-app 
[openui5-sample-app](https://github.com/SAP/openui5-sample-app)
```sh
cd openui5-sample-app
rm package-lock.json
touch .npmrc
```

.npmrc content:
```
registry=https://r.cnpmjs.org/
package-lock=true
```

execute
`npm install`

### Result
the result was a `package-lock.json` file which contained:
@ui5/builder
```
"@ui5/builder": {
			"version": "2.8.3",
			"resolved": "https://r.cnpmjs.org/@ui5/builder/download/@ui5/builder-2.8.3.tgz",
....
```
@ui5/cli
```
"@ui5/cli": {
			"version": "2.10.3",
			"resolved": "https://r.cnpmjs.org/@ui5/cli/download/@ui5/cli-2.10.3.tgz",
"dependencies": {
				"@ui5/builder": {
					"version": "2.8.3",
					"resolved": "https://registry.npmjs.org/@ui5/builder/-/builder-2.8.3.tgz",

```

Regards
Tobias

**Comment by RandomByte** [comment] 2021-05-03 08:54
Are only `@ui5`-scoped packages affected or also others?

**Comment by tobiasso85** [comment] 2021-05-03 08:58
> Are only `@ui5`-scoped packages affected or also others?

Also others:
dependencies > @ui5/cli > dependencies
```
				"JSONStream": {
					"version": "1.3.5",
					"resolved": "https://registry.npmjs.org/JSONStream/-/JSONStream-1.3.5.tgz",
```
But only dependencies of @ui5/cli

**Comment by RandomByte** [comment] 2021-05-03 16:30
I'm not sure what we can do here. `npm-shrinkwrap.json` is an npm feature. We use it for some [good reasons](https://github.com/SAP/ui5-tooling/issues/294) and I think we are using it correctly.

I think this is rather an issue/feature request for the npm CLI. It might also be worth checking on Yarns behavior here.

By the way, I confirmed the behavior as described by Tobias (but also removing `node_modules`) with npm v6.14.13 and v7.11.2 on Node v15.12.0.

**Comment by rishabh2408** [comment] 2021-05-04 14:56
As per https://doc.codingdict.com/npm-ref/files/shrinkwrap.html we should not publish the npm-shrinkwrap.json

**Comment by codeworrior** [comment] 2021-05-04 15:16
@rishabh2408 I read that page differently:

> The recommended use-case for npm-shrinkwrap.json is applications deployed through the publishing process on the registry: **_for example, daemons and command-line tools intended as global installs or devDependencies._** It's strongly discouraged for library authors to publish this file, since that would prevent end users from having control over transitive dependency updates.

@ui5/cli perfectly falls into the category command line tools. Well, I understand that even a CLI can be used as a library, but as @RandomByte pointed out, we had good reasons to include an  npm-shrinkwrap.json.

**Comment by RandomByte** [comment] 2021-05-10 09:11
I'm closing this issue since this is rather a feature request for the npm CLI.

Currently I don't see anything we can do without loosing the benefits of the shrinkwrap file for our project.

**Closed by RandomByte** 2021-05-10 09:11 UTC
Labels: bug
