### ISSUE TITLE
[@ui5/builder@2.11.3]: Unknown Task XXX

### ISSUE THREAD

**Issue by petermuessig** [SAP/ui5-tooling#592] opened 2021-12-26 09:46 UTC
## Expected Behavior
When using the UI5 Tooling in combination with Karma, configured middlewares in the `ui5.yaml` should be properly resolved and Karma will not fail on startup.

## Current Behavior
The Karma test fails with the issue `Unknown Task XXX`.

## Steps to Reproduce the Issue
1. Checkout https://github.com/ui5-community/ui5-ecosystem-showcase/pull/548/commits/c03108996c42c51a5069300d90af71409f535abb
2. Run `yarn --ignore-engines`
3. Run the AVA tests with `yarn workspace ui5-task-zipper test`
4. Result: **No issue**
5. Remove the `@ui5/builder@2.11.2` in the workspace root `package.json` and run `yarn --ignore-engines` again
6. Run the AVA tests with `yarn workspace ui5-task-zipper test` again
7. Result: **ERROR**

## Context
 * UI5 Module Version (output of `ui5 --version` when using the CLI): `2.14.2`
 * Node.js Version: `17.0.1`
 * Yarn Version: `1.22.17`
 * OS/Platform: `MacOS`
 * Browser *(if relevant)*: `not relevant`
 * Other information regarding your environment *(optional)*: `nothing`

## Log Output / Stack Trace

```sh
> ui5-ecosystem-showcase/packages/ui5-middleware-cfdestination [pr/548] M % yarn workspace ui5-task-zipper testyarn workspace v1.22.17
yarn run v1.22.17
$ ava

info
 normalizer:translators:ui5Framework Using OpenUI5 version: 1.91.0
info
 builder:builder Building project ui5-app not including dependencies...
info
 builder:builder 🛠  (1/1) Building project ui5-app
ERR! builder:builder Build failed in 5.86 ms
info
 builder:builder Executing cleanup tasks...

⚠️  Process Failed With Error

Error Message:
taskRepository: Unknown Task ui5-task-zipper
```

**Comment by matz3** [comment] 2022-01-10 09:55
Looks like a duplicate of https://github.com/SAP/ui5-tooling/issues/302

**Comment by RandomByte** [comment] 2022-01-12 16:47
See https://github.com/SAP/ui5-tooling/issues/591#issuecomment-1011243013

I'm also unable to checkout this commit, so I can't reproduce the issue. Please make sure that only one version of `@ui5/builder` is installed. Kindly share the output of `yarn list --pattern @ui5/builder`

**Closed by RandomByte** 2022-01-12 16:47 UTC
Labels: bug, needs triage
