### ISSUE TITLE
Invalid string length in projectPreprocessor

### ISSUE THREAD

**Issue by vinamogit** [SAP/ui5-tooling#645] opened 2022-08-03 17:33 UTC
## Expected Behavior

Build processor does not throw errors.

## Current Behavior

Get "Invalid string length" during ui5 build.

## Steps to Reproduce the Issue

1. Have a lot of dependencies (maybe?)
2. Build

## Context
 * UI5 Module Version (output of `ui5 --version` when using the CLI): **`2.14.10`**
 * Node.js Version: **`v17.7.1`**
 * npm Version: `8.5.5`
 * OS/Platform: `macOS 12.4`

## Log Output / Stack Trace

```

Error Message:
Invalid string length

Stack Trace:
RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at ProjectPreprocessor.loadProjectConfiguration (/Project/node_modules/@ui5/cli/node_modules/@ui5/project/lib/projectPreprocessor.js:235:40)
```

Replacing 
[const projectClone = structuredClone(project);](https://github.com/SAP/ui5-project/blob/9bd921a05bd5c0d8b6c6d94a864e60e4e181ad63/lib/projectPreprocessor.js#L234)
by 
```
const projectClone = structuredClone(project);
```
seems to work.

**Comment by RandomByte** [comment] 2022-08-03 22:57
Thank you for reporting!

Based on what you wrote, could you please try the workaround outlined in https://github.com/SAP/ui5-tooling/issues/311#issuecomment-779401749 and see whether that helps?

Also, is there a way we could reproduce this issue? If you can nail it down to the amount of dependencies, could you maybe share that part (dependencies, devDependencies) of your package.json with us? Thanks!

**Comment by vinamogit** [comment] 2022-08-03 23:21
Hi,

I changed my dependencies from:
```
  "dependencies": {
    "@sap/ux-ui5-tooling": "^1.1.2",
    "@ui5/cli": "^2.14.10",
    "web-ext": "^7.1.1"
  },
  "devDependencies": {
    "grunt": "^1.5.3",
    "grunt-contrib-compress": "2.0.0",
    "grunt-contrib-jshint": "^3.2.0",
    "grunt-contrib-nodeunit": "^4.0.0",
    "grunt-contrib-uglify": "^5.2.2",
    "grunt-remove-js-comments": "^0.1.2"
  }
```
to this:
```
  "dependencies": {
    "@sap/ux-ui5-tooling": "^1.1.2",
    "@ui5/cli": "^2.14.10"
  },
  "devDependencies": {
    "grunt": "^1.5.3",
    "grunt-contrib-compress": "2.0.0",
    "grunt-contrib-jshint": "^3.2.0",
    "grunt-contrib-nodeunit": "^4.0.0",
    "grunt-contrib-uglify": "^5.2.2",
    "grunt-remove-js-comments": "^0.1.2",
    "web-ext": "^7.1.1"
  }
```
and the problem does not appears anymore.
I have this project for some time now but didn't notice that I was running a 0.1 version of UI5, this error happened today when I updated to the latest version.

Regards.

**Comment by RandomByte** [comment] 2022-08-04 08:21
Thank you for providing those details. I was able to reproduce the issue, even though with a different error.

With your first dependency configuration, I got "FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory" as also reported in https://github.com/SAP/ui5-tooling/issues/311

Since you only `@sap/ux-ui5-tooling` seems to contain resources relevant to UI5 Tooling, you can configure the tooling to ignore all other dependencies by adding the following to your package.json:

```diff
  "dependencies": {
    "@sap/ux-ui5-tooling": "^1.1.2",
    "@ui5/cli": "^2.14.10",
    "web-ext": "^7.1.1"
  },
  "devDependencies": {
    "grunt": "^1.5.3",
    "grunt-contrib-compress": "2.0.0",
    "grunt-contrib-jshint": "^3.2.0",
    "grunt-contrib-nodeunit": "^4.0.0",
    "grunt-contrib-uglify": "^5.2.2",
    "grunt-remove-js-comments": "^0.1.2"
  },
+  "ui5": {
+    "dependencies": ["@sap/ux-ui5-tooling"]
+  }
```

This should speed up the tooling execution too. I will close this issue as duplicate of https://github.com/SAP/ui5-tooling/issues/311

*I was also able to confirm that (as hoped) the current alpha release of UI5 Tooling v3 does not have this issue and resolves all dependencies within ~250ms*

**Closed by RandomByte** 2022-08-04 08:21 UTC
Labels: bug, needs triage
